/* Synthetic operator scenario; all workspace writes go through the GUI. */
const {chromium}=require('playwright');
const {spawn,spawnSync}=require('node:child_process');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),url='http://127.0.0.1:8878',output=path.join(root,'test-output',`composition-${Date.now()}`);
let server,browser,page,db='workspace.sqlite3';const errors=[],expectedHttpErrors=[];
async function start(){server=spawn('python',['-m','app.server','--no-browser','--port','8878','--db',path.join(output,db)],{cwd:root,windowsHide:true,env:{...process.env,PYTHONUTF8:'1'}});let log='';server.stdout.on('data',c=>log+=c);server.stderr.on('data',c=>log+=c);for(let i=0;i<100;i++){if(log.includes('http://'))return;if(server.exitCode!==null)throw Error(log);await new Promise(r=>setTimeout(r,100));}throw Error(log);}
async function stop(){if(server?.exitCode===null)await new Promise(r=>{server.once('exit',r);server.kill();});}
async function initial(){await page.goto(url);await page.locator('#save-status').filter({hasText:'Сохранено'}).waitFor();}
async function snapshot(){return (await (await fetch(url+'/api/state')).json());}
async function submit(label='Сохранить'){await page.locator('#modal-form').getByRole('button',{name:label,exact:true}).click();await page.locator('#dialog').waitFor({state:'hidden'});await page.waitForFunction(()=>!document.body.classList.contains('busy'));}
async function create(word){await page.locator('#new-study').click();await page.locator('#modal-form [name="title"]').fill(word);await submit('Создать');}
async function select(id){await page.locator('#node-search').fill(id);await page.locator(`#node-list [data-node="${id}"]`).click();}
async function add(label,combo=false){await page.locator(combo?'#add-combination':'#add-independent').click();if(label)await page.locator('#modal-form [name="label"]').fill(label);await submit('Добавить');const s=(await snapshot()).state.studies[0];return s.nodes.at(-1).id;}
async function link(from,to,component=false,type=''){await select(from);await page.locator(component?'#include-component':'#link-node').click();await page.locator('#modal-form [name="to"]').fill(to);await page.locator('#modal-form [name="type"]').fill(type);await submit();}
async function replacement(source,target){await select(source);await page.locator('#replace-concept').click();await page.locator('#modal-form [name="targetId"]').selectOption(target);await page.locator('#modal-form').getByRole('button',{name:'Проверить',exact:true}).click();await page.locator('#dialog h2').filter({hasText:'Проверка замещения'}).waitFor();}
async function confirmReplacement(){await page.locator('#modal-form [name="confirmed"]').check();await page.locator('#modal-form [name="reason"]').fill('Синтетическое ручное решение для проверки инструмента, не научный вывод');await submit('Подтвердить замещение');}
async function importDoc(doc){await page.locator('[data-view="exchange"]').click();await page.locator('#import-text').fill(JSON.stringify(doc));await page.locator('#stage-import').click();await submit('Добавить в очередь');}
async function accept(){await page.locator('#select-proposals').click();await page.locator('#accept-proposals').click();await submit('Принять');}
(async()=>{
 await fs.mkdir(output,{recursive:true});await start();browser=await chromium.launch({channel:'chrome',headless:true});page=await browser.newPage({viewport:{width:1580,height:1050}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'){if(m.text().includes('400 (Bad Request)'))expectedHttpErrors.push(m.text());else errors.push(m.text());}});await initial();
 await create('X — синтетическое исследование');const sid=(await snapshot()).state.studies[0].id,X=(await snapshot()).state.studies[0].rootId;
 const hardness=await add('твёрдость'),modifier=await add('модификатор'),property=await add('свойство'),alpha=await add('',true);
 assert.equal(await page.locator('#node-form [name="label"]').inputValue(),'');assert.equal(await page.locator('#node-form [name="structure"]').inputValue(),'combination');
 await link(alpha,hardness,true);await link(alpha,modifier,true);await link(alpha,property,true);await link(X,alpha,false,'характеристика целого');
 const beta=await add('β',true);await link(beta,alpha,true);const gamma=await add('',true);await link(gamma,property,true);await link(X,gamma,false,'другое утверждение');
 let snap=await snapshot(),s=snap.state.studies[0];assert.equal(s.edges.filter(e=>e.role==='relation'&&e.to===property).length,0);assert.notEqual(alpha,gamma);assert.equal(snap.state.matches.length,0);
 // Establish X as start, then navigate using actual links through beta / alpha / components.
 await link(X,beta);await page.locator(`[data-study="${sid}"]`).click();const navBefore=await snapshot();
 await page.locator('#inspector [data-go]').filter({hasText:'Перейти'}).last().click();assert.equal(await page.locator('#node-form [name="label"]').inputValue(),'β');
 await page.locator('#graph [data-graph-node="'+alpha+'"]').click();assert.equal(await page.locator('#node-form [name="label"]').inputValue(),'');
 assert.equal(await page.locator('#graph [data-graph-node="'+X+'"]').count(),0);await page.locator('#graph [data-graph-node="'+hardness+'"]').click();
 await page.locator('#nav-back').click();assert.equal(await page.locator('#node-form [name="structure"]').inputValue(),'combination');await page.locator('#nav-back').click();assert.equal(await page.locator('#node-form [name="label"]').inputValue(),'β');await page.locator('#nav-origin').click();assert.equal(await page.locator('#node-form [name="label"]').inputValue(),'X — синтетическое исследование');assert.deepEqual(await snapshot(),navBefore);
 await select(alpha);await page.locator('#add-designation').click();await page.locator('#modal-form [name="text"]').fill('структурное обозначение');await submit();await page.locator('#node-search').fill('структурное обозначение');assert.equal(await page.locator('#node-list [data-node]').count(),1);
 const word=await add('твёрдый');await link(X,word,false,'свойство');await link(word,modifier,false,'пояснение');const beforeReplace=await snapshot();
 await replacement(word,alpha);await confirmReplacement();s=(await snapshot()).state.studies[0];assert(!s.nodes.some(n=>n.id===word));assert(s.designations.some(d=>d.text==='твёрдый'&&d.target===alpha));assert(s.edges.some(e=>e.from===X&&e.to===alpha&&e.type==='свойство'));assert(s.edges.some(e=>e.from===alpha&&e.to===modifier&&e.role==='relation'));assert(s.nodes.find(n=>n.id===alpha).origins.some(o=>o.snapshot.id===word));
 await page.locator('#composition-actions details').first().locator('summary').click();await page.locator('[data-undo-substitution]').click();await submit('Восстановить концепт');s=(await snapshot()).state.studies[0];assert.deepEqual(s.nodes,beforeReplace.state.studies[0].nodes);assert.deepEqual(s.edges,beforeReplace.state.studies[0].edges);assert.equal(s.substitutions[0].status,'restored');
 await replacement(word,alpha);await confirmReplacement();await page.locator('#node-form [name="notes"]').fill('Изменённый контекст после замещения');await page.locator('#node-form button[type="submit"]').click();await page.waitForFunction(()=>!document.body.classList.contains('busy'));const changed=await snapshot();
 await page.locator('#composition-actions details').last().locator('summary').click();await page.locator('[data-undo-substitution]').click();await page.locator('#modal-form').getByRole('button',{name:'Восстановить концепт',exact:true}).click();await page.locator('#toast.error').filter({hasText:'контекст изменился'}).waitFor();assert.deepEqual(await snapshot(),changed);await page.locator('#modal-cancel').click();
 // Self-definition and resulting self-loop must be visible blockers, never silent rewrites.
 await replacement(modifier,alpha);await page.locator('.replacement-problem').first().waitFor();assert.equal(await page.locator('[name="confirmed"]').count(),0);await page.locator('#modal-close').click();assert.deepEqual(await snapshot(),changed);
 await page.locator('#toast').waitFor({state:'hidden'});await select(beta);await page.screenshot({path:path.join(output,'nested-composition.png'),fullPage:true});await select(alpha);await page.screenshot({path:path.join(output,'substitution.png'),fullPage:true});
 const download=page.waitForEvent('download');await page.locator('#export-study').click();await (await download).saveAs(path.join(output,'study-v2.json'));const doc=JSON.parse(await fs.readFile(path.join(output,'study-v2.json'),'utf8'));assert.equal(doc.version,2);assert(doc.history.length>0);
 await importDoc(doc);assert.equal((await snapshot()).state.proposals.filter(p=>p.status==='pending').length,0);
 // Full history restoration preserves composition and substitution evidence.
 await page.locator('[data-view="history"]').click();await page.locator(`[data-restore="${beforeReplace.revision}"]`).click();await submit('Восстановить');assert.deepEqual((await snapshot()).state,beforeReplace.state);await page.locator(`[data-restore="${changed.revision}"]`).click();await submit('Восстановить');assert.deepEqual((await snapshot()).state,changed.state);
 await stop();await start();await initial();assert.deepEqual((await snapshot()).state,changed.state);
 // Fresh database v2 import, then legacy v1 import with disjoint spaces, repeat and reopen.
 await stop();db='fresh.sqlite3';await start();await initial();await importDoc(doc);await accept();s=(await snapshot()).state.studies[0];assert.deepEqual(s,changed.state.studies[0]);const legacy=JSON.parse(await fs.readFile(path.join(root,'data/fixtures/manual-example.json'),'utf8'));await importDoc(legacy);await accept();snap=await snapshot();assert.equal(snap.state.studies.length,3);const ids=snap.state.studies.flatMap(s=>s.nodes.map(n=>n.id));assert.equal(new Set(ids).size,ids.length);await importDoc(legacy);assert.equal((await snapshot()).state.proposals.filter(p=>p.status==='pending').length,0);
 // Compare anonymous combinations: no candidates from a blank label.
 await create('Независимая комбинация');await page.locator('#add-combination').click();await submit('Добавить');await page.locator('[data-view="compare"]').click();await page.locator('#compare-left').selectOption(sid);const independent=(await snapshot()).state.studies.at(-1);await page.locator('#compare-right').selectOption(independent.id);assert.equal(await page.locator('#matches [data-select-pair]').count(),0);
 // A reviewed deletion of the viewed combination clears stale traversal context.
 await page.locator('[data-view="editor"]').click();const removed=independent.nodes.at(-1);await select(removed.id);await importDoc({format:'concept-field-graph',version:2,kind:'changes',changes:[{operation:'delete_node',studyId:independent.id,base:removed,value:{id:removed.id}}]});await accept();await page.locator('[data-view="editor"]').click();assert.equal(await page.locator('#node-form [name="label"]').inputValue(),'Независимая комбинация');assert.equal(await page.locator('#nav-origin').isDisabled(),true);
 const persisted=(await snapshot()).state;await stop();await start();await initial();assert.deepEqual((await snapshot()).state,persisted);await page.locator(`[data-study="${sid}"]`).click();await select(alpha);await page.locator('#node-form [name="alternatives"]').fill('Продолжение после перезапуска');await page.locator('#node-form button[type="submit"]').click();await page.waitForFunction(()=>!document.body.classList.contains('busy'));

 // A large anonymous composition is imported in bulk and explored with bounded graph/list DOM.
 const generated=spawnSync('python',['-c','import json; from scripts.fixtures import large_composition; print(json.dumps(large_composition(),ensure_ascii=False))'],{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024,env:{...process.env,PYTHONUTF8:'1'}});assert.equal(generated.status,0,generated.stderr);
 const largeDoc=JSON.parse(generated.stdout);await importDoc(largeDoc);await accept();const large=largeDoc.state.studies[0];await page.locator(`[data-study="${large.id}"]`).click();await page.locator('#enter-combination').click();assert.equal(await page.locator('#graph .node').count(),15);assert.equal(await page.locator('#inspector .relation-item').count(),60);assert.equal(await page.locator('#node-list .node-item').count(),80);await select(large.nodes.at(-1).id);assert.equal(await page.locator('#node-form [name="label"]').inputValue(),'Компонент 1999');assert.equal(await page.locator('#graph [data-graph-node="'+large.nodes.at(-1).id+'"]').count(),1);await page.locator('#nav-back').click();assert(await page.locator('#graph').evaluate(e=>e.getBoundingClientRect().height)<1050);assert(await page.evaluate(()=>document.documentElement.scrollHeight)<1800);await page.screenshot({path:path.join(output,'large-composition.png'),fullPage:true});
 assert.deepEqual(errors,[]);assert.equal(expectedHttpErrors.length,1);await fs.writeFile(path.join(output,'report.json'),JSON.stringify({result:'passed',browser:await browser.version(),node:process.version,scenario:'anonymous alpha; directed membership/reuse; whole assertion; beta/alpha navigation and return without writes; shared component without inference; dictionary; preview/confirmed substitution/undo; changed-context and ambiguity blockers; v2 export/idempotent import/fresh import; full history; v1 preservation and isolation; anonymous comparison; reviewed removal clears traversal; process restart and continued editing; 2000-component bulk import and bounded exploration',pageErrors:errors,expectedHttpRejections:expectedHttpErrors.length},null,2));console.log('Composition browser passed. Evidence: '+output);
})().catch(async e=>{if(page)await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();await stop();});
